module.exports = [
  'Thanks for using new-component!',
  'Thanks for using new-component!',
  'Thanks for using new-component!',
  'Thanks for using new-component!',
  'Thanks for using new-component!',
  "Hope you're having a great day!",
  "Hope you're having a lovely day!",
  "Hope you're having a stellar day!",
  "Hope you're having a glorious day!",
  "Hope you're having a marvelous day!",
  "Hope you're having a brilliant day!",
  "Hope you're having a wonderful day!",
  "Hope you're having a fantastic day!",
  "Hope you're having a phenomenal day!",
  "Hope you're having a sensational day!",
  "Hope you're having an incredible day!",
  "Hope you're having the best day ever!",
  'An apple a day keeps the doctor away. 🍎',
  "Can't wait what to see what you do with it!",
  'Same bat time, same bat channel. 🦇',
  'Be kind, rewind.',
  'Every day is an adventure. ✨',
  "You miss 100% of the shots you don't take. 🏀",
  "It's like sunshine on a rainy day. 🌦",
  "💪 Let's do this.",
  "💪 Let's go!",
  "💪 You've got this.",
  "You're a rockstar. 🤘",
  'Have you gone for a walk today? 🚶',
  'Be kind to people. Including yourself.',
  'Woohoo!! ✨',
  "Let's do some celebratory jumping jacks! ⭐️",
  "Let's party 🥳",
  'All good vibes. 🌈',
  '🎉🎉🎉🎉🎉',
  'You are an unstoppable force of nature.',
  'Turn up the jam. 🔊',
  'You belong in this world ❤️',
  'Live your best life ❤️',
  "Wherever it takes me, I'm down for the ride. 🎶",
];
